In [3]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [4]:
df = pd.read_csv("Iris.csv")

In [5]:
df.shape

(150, 6)

In [6]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [8]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:

df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [15]:
df.sort_index(axis=1, ascending=False)

,Id,PetalLengthCm,PetalWidthCm,SepalLengthCm,SepalWidthCm,Species
0,1,1.4,0.2,5.1,3.5,Iris-setosa
1,2,1.4,0.2,4.9,3.0,Iris-setosa
2,3,1.3,0.2,4.7,3.2,Iris-setosa
3,4,1.5,0.2,4.6,3.1,Iris-setosa
4,5,1.4,0.2,5.0,3.6,Iris-setosa
...,...,...,...,...,...,...
145,146,5.2,2.3,6.7,3.0,Iris-virginica
146,147,5.0,1.9,6.3,2.5,Iris-virginica
147,148,5.2,2.0,6.5,3.0,Iris-virginica
148,149,5.4,2.3,6.2,3.4,Iris-virginica
149,150,5.1,1.8,5.9,3.0,Iris-virginica

In [16]:
df.sort_values(by="SepalLengthCm")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
13,14,4.3,3.0,1.1,0.1,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
...,...,...,...,...,...,...
122,123,7.7,2.8,6.7,2.0,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica

In [ ]:
# 4. DATA PREPROCESSING

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [18]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [20]:
df.isnull()

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [23]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
 # 5. DATA FORMATTING

In [24]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [27]:
df["Id"] = df["Id"].astype(float)

In [28]:
df.dtypes

Id               float64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [ ]:
# 5. DATA NORMALIZATION

In [31]:
min_val = df['SepalLengthCm'].min()
max_val = df['SepalLengthCm'].max()
df['SepalLength_Norm'] = (df['SepalLengthCm'] - min_val) / (max_val - min_val)
print(df['SepalLength_Norm'])

0      0.222222
1      0.166667
2      0.111111
3      0.083333
4      0.194444
         ...
145    0.666667
146    0.555556
147    0.611111
148    0.527778
149    0.444444
Name: SepalLength_Norm, Length: 150, dtype: float64

In [32]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [40]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Species_Label'] = le.fit_transform(df['Species'])
print(df['Species_Label'].head())

0    0
1    0
2    0
3    0
4    0
Name: Species_Label, dtype: int32

In [37]:
df_onehot = pd.get_dummies(df, columns=['Species'])
print(df_onehot)

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1.0            5.1           3.5            1.4           0.2
1      2.0            4.9           3.0            1.4           0.2
2      3.0            4.7           3.2            1.3           0.2
3      4.0            4.6           3.1            1.5           0.2
4      5.0            5.0           3.6            1.4           0.2
..     ...            ...           ...            ...           ...
145  146.0            6.7           3.0            5.2           2.3
146  147.0            6.3           2.5            5.0           1.9
147  148.0            6.5           3.0            5.2           2.0
148  149.0            6.2           3.4            5.4           2.3
149  150.0            5.9           3.0            5.1           1.8

     SepalLength_Normalized  SepalLength_Norm  Species_Label  \
0                  0.222222          0.222222              0
1                  0.166667          0.166667              0
2                  0.111111          0.111111              0
3                  0.083333          0.083333              0
4                  0.194444          0.194444              0
..                      ...               ...            ...
145                0.666667          0.666667              2
146                0.555556          0.555556              2
147                0.611111          0.611111              2
148                0.527778          0.527778              2
149                0.444444          0.444444              2

     Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica
0                   True                    False                   False
1                   True                    False                   False
2                   True                    False                   False
3                   True                    False                   False
4                   True                    False                   False
..                   ...                      ...                     ...
145                False                    False                    True
146                False                    False                    True
147                False                    False                    True
148                False                    False                    True
149                False                    False                    True

[150 rows x 11 columns]

In [39]:
df_dummy = pd.get_dummies(df, columns=['Species'], drop_first=True)
print(df_dummy)

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1.0            5.1           3.5            1.4           0.2
1      2.0            4.9           3.0            1.4           0.2
2      3.0            4.7           3.2            1.3           0.2
3      4.0            4.6           3.1            1.5           0.2
4      5.0            5.0           3.6            1.4           0.2
..     ...            ...           ...            ...           ...
145  146.0            6.7           3.0            5.2           2.3
146  147.0            6.3           2.5            5.0           1.9
147  148.0            6.5           3.0            5.2           2.0
148  149.0            6.2           3.4            5.4           2.3
149  150.0            5.9           3.0            5.1           1.8

     SepalLength_Normalized  SepalLength_Norm  Species_Label  \
0                  0.222222          0.222222              0
1                  0.166667          0.166667              0
2                  0.111111          0.111111              0
3                  0.083333          0.083333              0
4                  0.194444          0.194444              0
..                      ...               ...            ...
145                0.666667          0.666667              2
146                0.555556          0.555556              2
147                0.611111          0.611111              2
148                0.527778          0.527778              2
149                0.444444          0.444444              2

     Species_Iris-versicolor  Species_Iris-virginica
0                      False                   False
1                      False                   False
2                      False                   False
3                      False                   False
4                      False                   False
..                       ...                     ...
145                    False                    True
146                    False                    True
147                    False                    True
148                    False                    True
149                    False                    True

[150 rows x 10 columns]